DELETE FROM USER_ROLE;
DELETE FROM MEAL;
DELETE FROM RESTAURANT;
DELETE FROM USERS;
ALTER SEQUENCE GLOBAL_SEQ RESTART WITH 100000;

INSERT INTO USERS (NAME, EMAIL, PASSWORD)
VALUES ('User', 'user@mail.ru', 'user');
INSERT INTO USERS (NAME, EMAIL, PASSWORD)
VALUES ('Admin', 'admin@mail.ru', 'admin');

INSERT INTO RESTAURANT (NAME, ADMIN_ID)
VALUES ('Restaurant', 100001);
INSERT INTO RESTAURANT (NAME, ADMIN_ID)
VALUES ('Kafe', 100001);

INSERT INTO MEAL (DESCRIPTION, PRICE, RESTAURANT_ID)
VALUES ('gerkules', 150, 100002);
INSERT INTO MEAL (DESCRIPTION, PRICE, RESTAURANT_ID)
VALUES ('kompot', 30, 100002);
INSERT INTO MEAL (DESCRIPTION, PRICE, RESTAURANT_ID, IS_CURRENT)
VALUES ('omlet', 100, 100002, FALSE);
INSERT INTO MEAL (DESCRIPTION, PRICE, RESTAURANT_ID)
VALUES ('lagman', 550, 100003);
INSERT INTO MEAL (DESCRIPTION, PRICE, RESTAURANT_ID)
VALUES ('kakao', 300, 100003);

INSERT INTO USER_ROLE (USER_ID, ROLE)
VALUES (100000, 'USER');
INSERT INTO USER_ROLE (USER_ID, ROLE)
VALUES (100001, 'ADMIN');


